console.log("Hello world");
var x=10;
let y=20;
console.log(x);
console.log(x+y);
console.log (x==y);
console.log(x===y);
let i,j,k;
console.log(k);
console.log(x)
var x=20;
console.log(x);
//naming variables
let q=5;
let _q=12;
let $q=1;
 // let 1q=22;
console.log(q);
console.log(_q);
console.log($q);
// console.log(1q);
const firstname="santhiya";
const lastname ="shivanya raj"
console.log(firstname+lastname);
console.log(firstname+" "+lastname);
console.log(`${firstname} ${lastname}`);
const s=3;
console.log(s);
console.log("hello"-"hi");
console.log(4+true);
console.log(5+false);
console.log(9+null);
console.log(null-9);
console.log(false-3);
const name= "santhiya";
console.log(typeof name);
var u=11
console.log(typeof u);
var u=11
console.log(typeof "u");
const symbol ='$';
console.log(typeof symbol );
var sym="$";
console.log(typeof sym);
const body="false";
console.log(typeof false);
const body1=null;
console.log(typeof null);
const body2 ="null";
console.log(typeof null);
console.log(Number("3"));
console.log(parseInt('3'));
console.log("3");
console.log(s==s);
console.log("s"=="s");
console.log("s"==="S");
console.log(1+1);
console.log(1-1);
console.log("1"+"1");
console.log("1"-"1");
console.log("1"-1);
console.log(1-"1");
console.log(1+"1");
console.log(1==1);
console.log("1"=="1");
console.log(1=="1");
console.log(1==="1");
console.log("1"==="1");
console.log(true=="0");
